version: "3.9"
services:
  app:
    build: .
    environment:
      - DB_HOST=postgres
    ports:
      - "7070:7070"
    depends_on:
      - postgres
    profiles:
      - app

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
